name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: developer
          POSTGRES_PASSWORD: developer
          POSTGRES_DB: coffee_mate_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          go test -v ./tests/... -covermode=count
